# -*- coding: utf-8 -*-
"""QRCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4ObKtmo6sN_nv-CB4MXDMbSoyireEGX
"""

!pip install pyqrcode

!pip install pypng

import pyqrcode
import png
from pyqrcode import QRCode 

s = "linkedin.com/in/vignesh-m-b0716a206"

url = pyqrcode.create(s)

url.svg("myqrforlinkedin.svg", scale = 8)

url.png('myqrforlinkedin.png', scale = 6)